### ISSUE TITLE
Errors with test_loadtxt_qp.exe and test_savetxt_qp.exe on Windows

### ISSUE THREAD

**Issue by Beliavsky** [LKedward/stdlib-fpm#24]
Running `fpm build` and then `fpm test` on Windows, most programs run, but then I get this:

```
  test_cdp_2dim_mask_array
<ERROR> Execution failed for object " test_loadtxt_qp.exe "
<ERROR> Execution failed for object " test_savetxt_qp.exe "
<ERROR>*cmd_run*:stopping due to failed executions
STOP 1
```

**Comment by LKedward** [comment]
Thanks for reporting @Beliavsky - may I ask which compiler and compiler version you are using?

**Comment by Beliavsky** [comment]
I am using GNU Fortran (GCC) 12.0.0 20210718 from equation.com on Windows. When I try to run the executables individually I get this:

```
c:\fortran\public_domain\github\stdlib-fpm\build\gfortran_2A42023B310FA28D\test>test_loadtxt_qp.exe
At line 950 of file .\src\stdlib_io.f90
Fortran runtime error: Cannot open file 'array4.dat': No such file or directory

c:\fortran\public_domain\github\stdlib-fpm\build\gfortran_2A42023B310FA28D\test>test_savetxt_qp.exe

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

**Comment by LKedward** [comment]
Thanks for that information. Do you get the same issue when using that compiler version with the upstream [`stdlib`](https://github.com/fortran-lang/stdlib) repository?

**Comment by Beliavsky** [comment]
Yes. Downloading the current stdlib, running `make -f Makefile.manual FYPPFLAGS=-DMAXRANK=4` and then running the executables gives

```
c:\fortran\public_domain\github\stdlib\src\tests\io>test_savetxt_qp.exe

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x44fb9b
#1  0x445a64
#2  0x41be61
#3  0x79f2ad57
#4  0x7a2e826e
#5  0x7a2759c9
#6  0x7a2e727d
#7  0xffffffff

c:\fortran\public_domain\github\stdlib\src\tests\io>test_loadtxt_qp.exe

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x43dedb
#1  0x433da4
#2  0x41a4f1
#3  0x79f2ad57
#4  0x7a2e826e
#5  0x7a2759c9
#6  0x7a2e727d
#7  0xffffffff
```

**Comment by LKedward** [comment]
Okay - can you [open a bug report in stdlib](https://github.com/fortran-lang/stdlib/issues/new?assignees=&labels=bug&template=01_bug.yaml) with all these details? I'm archiving this repository, since its functionality is now available upstream, and so I'll close this issue here.
