### ISSUE TITLE
Error building on WSL

### ISSUE THREAD

**Issue by Beliavsky** [LKedward/stdlib-fpm#8]
Try to install using fpm on WSL, I get this error:

fpm build
 + mkdir -p build/dependencies
Initialized empty Git repository in /mnt/c/fortran/public_domain/github/stdlib-fpm/build/dependencies/stdlib/.git/
From https://github.com/LKedward/stdlib-fpm
 * branch            HEAD       -> FETCH_HEAD
 + mkdir -p build/gfortran_debug/stdlib-fpm
 + gfortran -c test/check.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/test_check.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_ascii.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_ascii.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_kinds.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_kinds.f90.o
 + gfortran -c ././src/stdlib-fpm.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/src_stdlib-fpm.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_string_type.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_string_type.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_system.F90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_system.F90.o
build/dependencies/stdlib/src/stdlib_system.F90:31:16:

   31 | subroutine sleep(millisec)
      |                1
Warning: ‘sleep’ declared at (1) may shadow the intrinsic of the same name.  In order to call the intrinsic, explicit INTRINSIC declarations may be required. [-Wintrinsic-shadow]
 + gfortran -c app/main.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/app_main.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_linalg.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_linalg.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_bitsets.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_bitsets.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_optval.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_optval.f90.o
build/dependencies/stdlib/src/stdlib_bitsets.f90:33:37:

   33 |         overflow_bits = 2_bits_kind**30/5 ! bits_kind == int32
      |                                     1
Warning: Integer division truncated to constant ‘214748364’ at (1) [-Winteger-division]
 + gfortran -c build/dependencies/stdlib/src/stdlib_quadrature.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_quadrature.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_stats.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_stats.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_linalg_diag.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_linalg_diag.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_bitsets_64.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_bitsets_64.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_error.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_error.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_bitsets_large.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_bitsets_large.f90.o
build/dependencies/stdlib/src/stdlib_bitsets_64.f90:436:26:

  436 |         self % num_bits = bits
      |                          1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
 + gfortran -c build/dependencies/stdlib/src/stdlib_logger.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_logger.f90.o
build/dependencies/stdlib/src/stdlib_logger.f90:1072:0:

 1072 |                     new_line('a') // 'With iomsg = "' // trim(iomsg) // '"'
      | 
Warning: ‘.suffix’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_logger.f90:926:0:

  926 |                     new_line('a') // 'With errmsg = "' // trim(errmsg) // '"'
      | 
Warning: ‘.suffix’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_logger.f90:1149:0:

 1149 |             pref = prefix // ': '
      | 
Warning: ‘.pref’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_logger.f90:1155:0:

 1155 |             d_and_t = time_stamp() // ': '
      | 
Warning: ‘.d_and_t’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_logger.f90:1162:0:

 1162 |                 m_and_p = trim(module) // ' % ' // trim(procedure) // ': '
      | 
Warning: ‘.m_and_p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 + gfortran -c build/dependencies/stdlib/src/f18estop.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_f18estop.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_quadrature_simps.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_quadrature_simps.f90.o
 + gfortran -c build/dependencies/stdlib/src/f08estop.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_f08estop.f90.o
 + gfortran -c build/dependencies/stdlib/src/stdlib_io.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_io.f90.o
f951: Fatal Error: Cannot rename module file ‘build/gfortran_debug/stdlib-fpm/stdlib_error@estop.smod0’ to ‘build/gfortran_debug/stdlib-fpm/stdlib_error@estop.smod’: No such file or directory
compilation terminated.
 Command failed
ERROR STOP 

Error termination. Backtrace:
 + gfortran -c build/dependencies/stdlib/src/stdlib_quadrature_trapz.f90 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -fcoarray=single  -J build/gfortran_debug/stdlib-fpm -I build/gfortran_debug/stdlib-fpm -o build/gfortran_debug/stdlib-fpm/build_dependencies_stdlib_src_stdlib_quadrature_trapz.f90.o
build/dependencies/stdlib/src/stdlib_io.f90:965:0:

  965 |     a=trim(adjustl(mode))
      | 
Warning: ‘.a’ may be used uninitialized in this function [-Wmaybe-uninitialized]
#0  0x559808bee2ec in ???
#1  0x559808bf5a4b in ???
#2  0x559808bf5d3c in ???
#3  0x7fd5b19f76c8 in gomp_thread_start
	at /home/conda/feedstock_root/build_artifacts/ctng-compilers_1610729750655/work/.build/x86_64-conda-linux-gnu/src/gcc/libgomp/team.c:123
build/dependencies/stdlib/src/stdlib_io.f90:896:0:

  896 |       action_='read'
      | 
Warning: ‘.action_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_io.f90:897:0:

  897 |       position_='asis'
      | 
Warning: ‘.position_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_io.f90:898:0:

  898 |       status_='old'
      | 
Warning: ‘.status_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_io.f90:933:0:

  933 |       form_='formatted'
      | 
Warning: ‘.form_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
build/dependencies/stdlib/src/stdlib_io.f90:940:0:

  940 |     access_ = 'stream'
      | 
Warning: ‘.access_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
#4  0x7fd5b1776608 in start_thread
	at /build/glibc-ZN95T4/glibc-2.31/nptl/pthread_create.c:477
#5  0x7fd5b1913292 in ???
#6  0xffffffffffffffff in ???

**Comment by LKedward** [comment]
Thanks for reporting @Beliavsky, this is indeed an error with this repo but it is also related to <https://github.com/fortran-lang/fpm/issues/396>. It looks like I've accidently included both submodule implementations of errorstop.

**Comment by LKedward** [comment]
I've now removed the offending duplicate submodule.
